# Generated by Django 4.1.3 on 2022-11-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(default='Prime numbers', max_length=100),
            preserve_default=False,
        ),
    ]
